export enum OrderStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  WAITING_STOCK = 'WAITING_STOCK',
  WAITING_PAYMENT = 'WAITING_PAYMENT',
  WAITING_SHIPPING = 'WAITING_SHIPPING',
  WAITING_DELIVERY = 'WAITING_DELIVERY',
}
