version: '3.8'
name: order
services:
  order:
    image: sciam/order-service:2.0
    ports:
      - 8090:8080
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      QUARKUS_REST_CLIENT_PAYMENT_API_URL: http://payment:8080
      KOGITO_SERVICE_URL: http://order:8080
      KOGITO_DATAINDEX_HTTP_URL: http://data-index:8080
      QUARKUS_FLYWAY_BASELINE_ON_MIGRATE: "true"
    volumes:
      - ./../target/classes/META-INF/processSVG/:/home/kogito/data/svg/
    networks:
      - kogito-net

  article-ui:
    image: sciam/article-ui:2.0
    ports:
      - 8091:8080
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      QUARKUS_REST_CLIENT_STOCK_API_URL: http://inventory:8080
    networks:
      - kogito-net

  inventory:
    image: sciam/order-inventory:2.0
    ports:
      - 8092:8080
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - kogito-net

  payment:
    image: sciam/order-payment:2.0
    ports:
      - 8094:8080
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KOGITO_SERVICE_URL: http://payment:8080
      KOGITO_DATAINDEX_HTTP_URL: http://data-index:8080
      QUARKUS_FLYWAY_BASELINE_ON_MIGRATE: "true"
    volumes:
      - ./svg/:/home/kogito/data/svg/
    networks:
      - kogito-net

networks:
  kogito-net:
    driver: bridge


